### ISSUE TITLE
Using Lucene Extensions to Run Hibernate Search Connected to Redis

### ISSUE THREAD

**Issue by gigincg** [DDTH/ddth-lucext#1]
Hi,
 I'm new to Hibernate Search and I am trying to implement Hibernate Search on my AWS Deployment which is connected to a 1 GB Redis instance that's quite under utilized. I don't want to connect to an Elastic Search instance at the moment and I am wondering if it is possible to host the Lucene indexes on Redis to work with Hibernate Search. I apologize if my intentions don't conform with the architecture that Lucene and Hibernate are built on.
 If the extensions that youy've built could possibly attain this, any pointers would be appreciated.

Thanks in advance

**Comment by btnguyen2k** [comment]
Hi @gigincg,

I don't use Hibernate Search so I can't confirm but my first impression is that you may not be able to do this. The reason is that with Hibernate Search you chose a "provider" from a list of predefined ones. Even if you can somehow "inject" new provider to Hibernate Search, you at least need to write a wrapper because this Lucene extension has interface for Lucence not for Hibernate Search.
Hence the direction you would take is to find a Redis provider for Hibernate Search, or write a wrapper around Lucene extension that comforts with Hibernate Search provider interface.

Regards,

**Comment by gigincg** [comment]
Thanks for the quick response! I'll try to do that. Great work you've done here. Closing the issue since it's not really an issue with your project.
